version: '3.7'

services:
  frontend:
    depends_on:
      - backend
      - db
    build:
      context: ./frontend
    container_name: frontend
    command: yarn dev
    stdin_open: true
    tty: true
    environment:
      - NEXT_PUBLIC_FRONTEND_TITLE=tips.gg
      - NEXT_PUBLIC_FRONTEND_DESC=game tips community
      - NODE_ENV=development
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:8080
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080/api
      - NEXT_PUBLIC_TOKEN_NAME=vst
      - NEXT_PUBLIC_FACEBOOK_APP_ID=156438079426181
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=721540730222-mt4bbuntpqusnrpb2gk1go380j45tkml.apps.googleusercontent.com
    volumes:
      - ./frontend/src:/usr/app/src
    ports:
      - '3000:3000'
  backend:
    depends_on:
      - db
    build:
      context: ./backend
    container_name: backend
    environment:
      - PORT=3001
      - DB_NAME=test
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - TOKEN_SECRET="VIABJcjti143"
      - TOKEN_NAME="vst"
      - SENDGRID_API_ENDPOINT='https://api.sendgrid.com/v3/mail/send'
      - SENDGRID_API_KEY='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'
      - SEND_GRID_TEMPLATE_ID='d-b3d2b0f5a38546018a7a8400bc9f1fcc'
      - FRONTEND_URI=localhost:8080
    command: start
    volumes:
      - ./backend/src:/usr/app/src
    ports:
      - '3001:3001'
  db:
    container_name: db_postgres
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
      LANG: LANG ja_JP.utf8
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  nginx:
    container_name: reverse_proxy
    image: nginx:1.18.0-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_db:
